"""change bet and match keys - for real v2

Revision ID: 06dc0ce76516
Revises: 5668de9a5397
Create Date: 2022-04-07 09:06:34.156456

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06dc0ce76516'
down_revision = '5668de9a5397'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bet')
    op.drop_table('bet_event')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bet_event',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('matchId', sa.INTEGER(), nullable=True),
    sa.Column('bettedOn', sa.VARCHAR(length=35), nullable=False),
    sa.Column('betId', sa.INTEGER(), nullable=False),
    sa.Column('date', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['betId'], ['bet.id'], ),
    sa.ForeignKeyConstraint(['matchId'], ['match.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bet',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
