"""add everything

Revision ID: 0d0f3cab2b47
Revises: 7ebf2383ab81
Create Date: 2022-04-07 09:11:16.386526

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d0f3cab2b47'
down_revision = '7ebf2383ab81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bet_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bettedOn', sa.String(length=35), nullable=False),
    sa.Column('betId', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['betId'], ['bet.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('match',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('time', sa.Time(), nullable=False),
    sa.Column('tier', sa.String(length=20), nullable=False),
    sa.Column('round', sa.String(length=20), nullable=False),
    sa.Column('firstPlayer', sa.String(length=35), nullable=False),
    sa.Column('secondPlayer', sa.String(length=35), nullable=False),
    sa.Column('firstOdds', sa.Float(), nullable=False),
    sa.Column('secondOdds', sa.Float(), nullable=False),
    sa.Column('result', sa.String(length=35), nullable=True),
    sa.Column('betId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['betId'], ['bet_event.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('match')
    op.drop_table('bet_event')
    op.drop_table('bet')
    # ### end Alembic commands ###
