"""remove not null for matchid

Revision ID: 2e5b67af96b3
Revises: 3d309f354463
Create Date: 2022-04-02 14:52:52.029983

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e5b67af96b3'
down_revision = '3d309f354463'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bet', type_='foreignkey')
    op.create_foreign_key(None, 'bet', 'user', ['user'], ['id'])
    op.drop_column('bet', 'bettedOn')
    op.drop_column('bet', 'matchId')
    op.alter_column('bet_event', 'matchId',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'bet_event', type_='foreignkey')
    op.create_foreign_key(None, 'bet_event', 'bet', ['betId'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bet_event', type_='foreignkey')
    op.create_foreign_key(None, 'bet_event', 'bet_event', ['betId'], ['id'])
    op.alter_column('bet_event', 'matchId',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('bet', sa.Column('matchId', sa.INTEGER(), nullable=False))
    op.add_column('bet', sa.Column('bettedOn', sa.VARCHAR(length=35), nullable=False))
    op.drop_constraint(None, 'bet', type_='foreignkey')
    op.create_foreign_key(None, 'bet', 'match', ['matchId'], ['id'])
    # ### end Alembic commands ###
