"""trying normal functioning

Revision ID: 33b68538ca5a
Revises: 0a8960126b70
Create Date: 2022-04-02 15:19:45.901249

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33b68538ca5a'
down_revision = '0a8960126b70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bet', schema=None) as batch_op:
        pass

    with op.batch_alter_table('bet_event', schema=None) as batch_op:
        pass

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bet_event', schema=None) as batch_op:
        pass

    with op.batch_alter_table('bet', schema=None) as batch_op:
        pass

    # ### end Alembic commands ###
