"""change bet and match keys - for real v3

Revision ID: 3c5172d531ee
Revises: 06dc0ce76516
Create Date: 2022-04-07 09:07:28.438628

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c5172d531ee'
down_revision = '06dc0ce76516'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('match', schema=None) as batch_op:
        pass

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('match', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('betId')

    op.drop_table('bet_event')
    op.drop_table('bet')
    # ### end Alembic commands ###
