"""add bets to db

Revision ID: 3d309f354463
Revises: a9a600b48bf4
Create Date: 2022-04-02 14:38:53.592436

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d309f354463'
down_revision = 'a9a600b48bf4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bet', sa.Column('user', sa.Integer(), nullable=False))
    op.drop_constraint(None, 'bet', type_='foreignkey')
    op.create_foreign_key(None, 'bet', 'bet', ['user'], ['id'])
    op.drop_column('bet', 'matchId')
    op.drop_column('bet', 'bettedOn')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bet', sa.Column('bettedOn', sa.VARCHAR(length=35), nullable=False))
    op.add_column('bet', sa.Column('matchId', sa.INTEGER(), nullable=False))
    op.drop_constraint(None, 'bet', type_='foreignkey')
    op.create_foreign_key(None, 'bet', 'match', ['matchId'], ['id'])
    op.drop_column('bet', 'user')
    # ### end Alembic commands ###
