"""add everything - again

Revision ID: 4358ea27eb4e
Revises: f351b0a058af
Create Date: 2022-04-07 09:24:07.428530

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4358ea27eb4e'
down_revision = 'f351b0a058af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('match',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('time', sa.Time(), nullable=False),
    sa.Column('tier', sa.String(length=20), nullable=False),
    sa.Column('round', sa.String(length=20), nullable=False),
    sa.Column('firstPlayer', sa.String(length=35), nullable=False),
    sa.Column('secondPlayer', sa.String(length=35), nullable=False),
    sa.Column('firstOdds', sa.Float(), nullable=False),
    sa.Column('secondOdds', sa.Float(), nullable=False),
    sa.Column('result', sa.String(length=35), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bet_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('matchId', sa.Integer(), nullable=True),
    sa.Column('bettedOn', sa.String(length=35), nullable=False),
    sa.Column('betId', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['betId'], ['bet.id'], ),
    sa.ForeignKeyConstraint(['matchId'], ['match.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bet_event')
    op.drop_table('bet')
    op.drop_table('match')
    # ### end Alembic commands ###
