"""remove everything

Revision ID: 7ebf2383ab81
Revises: 3c5172d531ee
Create Date: 2022-04-07 09:10:39.484496

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ebf2383ab81'
down_revision = '3c5172d531ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bet')
    op.drop_table('match')
    op.drop_table('bet_event')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bet_event',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('bettedOn', sa.VARCHAR(length=35), nullable=False),
    sa.Column('betId', sa.INTEGER(), nullable=False),
    sa.Column('date', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['betId'], ['bet.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('match',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('date', sa.DATE(), nullable=False),
    sa.Column('time', sa.TIME(), nullable=False),
    sa.Column('tier', sa.VARCHAR(length=20), nullable=False),
    sa.Column('round', sa.VARCHAR(length=20), nullable=False),
    sa.Column('firstPlayer', sa.VARCHAR(length=35), nullable=False),
    sa.Column('secondPlayer', sa.VARCHAR(length=35), nullable=False),
    sa.Column('firstOdds', sa.FLOAT(), nullable=False),
    sa.Column('secondOdds', sa.FLOAT(), nullable=False),
    sa.Column('result', sa.VARCHAR(length=35), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bet',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
