"""change bet and match keys

Revision ID: 9ee1beb8cfdc
Revises: fc5ccb623b09
Create Date: 2022-04-07 08:58:40.117507

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ee1beb8cfdc'
down_revision = 'fc5ccb623b09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bet_event', schema=None) as batch_op:
        pass

    with op.batch_alter_table('match', schema=None) as batch_op:
        pass

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('match', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('betId')

    with op.batch_alter_table('bet_event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('matchId', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(None, 'match', ['matchId'], ['id'])

    # ### end Alembic commands ###
