"""resultcheck add

Revision ID: a7160264032a
Revises: 65bc222a8089
Create Date: 2022-04-07 15:33:18.075647

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7160264032a'
down_revision = '65bc222a8089'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('resultChecked', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dates', schema=None) as batch_op:
        batch_op.drop_column('resultChecked')

    # ### end Alembic commands ###
