"""try putting new data

Revision ID: c22770a6adb6
Revises: ce233b4c8dec
Create Date: 2022-04-02 15:52:59.617237

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c22770a6adb6'
down_revision = 'ce233b4c8dec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bet_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('matchId', sa.Integer(), nullable=True),
    sa.Column('bettedOn', sa.String(length=35), nullable=False),
    sa.Column('betId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['betId'], ['bet.id'], ),
    sa.ForeignKeyConstraint(['matchId'], ['match.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bet_event')
    op.drop_table('bet')
    # ### end Alembic commands ###
