"""cleanup

Revision ID: ce233b4c8dec
Revises: 33b68538ca5a
Create Date: 2022-04-02 15:51:45.470613

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce233b4c8dec'
down_revision = '33b68538ca5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bet')
    op.drop_table('bet_event')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bet_event',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('matchId', sa.INTEGER(), nullable=False),
    sa.Column('bettedOn', sa.VARCHAR(length=35), nullable=False),
    sa.Column('betId', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['betId'], ['bet_event.id'], ),
    sa.ForeignKeyConstraint(['matchId'], ['match.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bet',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('matchId', sa.INTEGER(), nullable=False),
    sa.Column('bettedOn', sa.VARCHAR(length=35), nullable=False),
    sa.Column('user', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['matchId'], ['match.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
