"""betname unique

Revision ID: d12bfebfe76f
Revises: 3cb62343082e
Create Date: 2022-04-26 10:56:14.462799

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd12bfebfe76f'
down_revision = '3cb62343082e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bet', schema=None) as batch_op:
        pass

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bet', schema=None) as batch_op:
        pass

    # ### end Alembic commands ###
